"""add dates to database

Revision ID: c754d3786672
Revises: 53a9f9d0d502
Create Date: 2020-06-14 18:42:33.251493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c754d3786672'
down_revision = '53a9f9d0d502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('distillation_date', sa.Date(), nullable=True))
    op.drop_index('ix_session_name', table_name='session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_name', 'session', ['name'], unique=1)
    op.drop_column('session', 'distillation_date')
    op.drop_column('result', 'created_at')
    # ### end Alembic commands ###
